version: '3'
services:
  orion:
    image: fiware/orion
    container_name: orion-context-broker
    ports:
      - "1026:1026"
    command: -dbhost mongo
    depends_on:
      - mongo
    networks:
      - fiware_network

  mongo:
    image: mongo
    container_name: mongodbfiware orion/docker-compose.yml
    networks:
      - fiware_network

networks:
  fiware_network:
    driver: bridge